# Site settings
url: "https://cautious-couscous.netlify.com/"

# Build settings
markdown: kramdown

sass:
  style: compressed

defaults:
  -
    scope:
      path: 'admin'
    values:
      sitemap: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /actu/:year/:month/:day/:title/
      layout: post
      alt: image-alt

collections:
    ressources:
        output: true
        permalink: /:collection/:name

paginate: 6
paginate_path: "/actu/all/page:num"

exclude: ["Gemfile","Gemfile.lock","generate-photo-galleries.sh", "*.gallerie.conf", ".*.conf"]

gems:
 - jekyll-sitemap
 - jekyll-paginate
 - jekyll-assets

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

assets:
  compress:
    css: true
    js: true
  prefix: "/js"
  assets:
    - "*.js"
  digest: true
  sources:
    - "_js"
    
    
