# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://caoutious-couscous-28047.netlify.com/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: 'admin'
    values:
      sitemap: false
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: /actu/:year/:month/:day/:title/
      layout: post
      alt: image-alt

collections:
    ressources:
        output: true
        permalink: /:collection/:name

paginate: 6
paginate_path: "/actu/all/page:num"

exclude: ["Gemfile","Gemfile.lock","generate-photo-galleries.sh", "*.gallerie.conf", ".*.conf"]

gems:
 - jekyll-sitemap
 - jekyll-paginate

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/feed.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
