# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://yourdomain.com" # the base hostname & protocol for your site - used for feed.xml
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
    ressources:
        output: true
        permalink: /:collection/:name

gems:
 - jekyll-sitemap

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
