backend:
  name: github
  repo: scoutscathedralevolcan/cautious-couscous-a-netlify-playground
  branch: master

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Accueil"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/"}
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "history"
        label: "Histoire"
        file: "history.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/history"}
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Header Image", name: "header-img", required: false, widget: "image"}
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "home-section"
    label: "Section page d'accueil"
    folder: "_includes/home-section"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Contenu", name: "body", widget: "text"}

  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", default: "actu"}
    meta:
      - {label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "ressources"
    label: "Ressources"
    folder: "_ressources"
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string"}
    meta:
      - {label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "settings"
    label: "Options du site"
    editor:
      preview: false
    files:
      - name: "colors"
        label: "Colors"
        file: "_data/colors.yml"
        fields:
          - {label: "Contenu", name: "body", widget: "text"}
      - name: "sitemenu"
        label: "Menu principal"
        file: "_data/sitemenu.yml"
        fields:
          - {label: "Contenu", name: "body", widget: "text"}


