backend:
  name: github
  repo: scoutscathedralevolcan/cautious-couscous-a-netlify-playground
  branch: master

media_folder: "img/uploads" # Folder where user uploaded files should go

collections:
  - name: "post"
    label: "Actualité"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", default: "actu"}
    meta:
      - {label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "ressources"
    label: "Ressources"
    folder: "_ressources"
    sort: "date:desc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string", tagname: "h1"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string"}
    meta:
      - {label: "Date de publication", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}

  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Lien parmanent", name: "permalink", widget: "string", default: "/new-page-{{year}}-{{month}}-{{day}}{{year}}-{{slug}}"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Header Image", name: "header-img", required: false, widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}

  #- name: "pages"
    #label: "Pages"
    #files:
      #- name: "home"
        #label: "Accueil"
        #file: "index.md"
        #fields:
          #- {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          #- {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/"}
          #- {label: "Contenu", name: "body", widget: "markdown"}
      #- name: "history"
        #label: "Histoire"
        #file: "history.md"
        #fields:
          #- {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          #- {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/history"}
          #- {label: "Titre", name: "title", widget: "string"}
          #- {label: "Header Image", name: "header-img", required: false, widget: "image"}
          #- {label: "Contenu", name: "body", widget: "markdown"}
      #- name: "animation"
        #label: "Animation"
        #file: "animation.md"
        #fields:
          #- {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          #- {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/animation"}
          #- {label: "Titre", name: "title", widget: "string"}
          #- {label: "Header Image", name: "header-img", required: false, widget: "image"}
          #- {label: "Contenu", name: "body", widget: "markdown"}
      #- name: "gestion"
        #label: "Gestion"
        #file: "gestion.md"
        #fields:
          #- {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          #- {label: "Lien parmanent", name: "permalink", widget: "hidden", default: "/gestion"}
          #- {label: "Titre", name: "title", widget: "string"}
          #- {label: "Header Image", name: "header-img", required: false, widget: "image"}
          #- {label: "Contenu", name: "body", widget: "markdown"}

  - name: "home-section"
    label: "Sections de la page d'accueil"
    files:
      - name: "about"
        label: "À propos"
        file: "_includes/home-section/about.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "front-message"
        label: "Information mise à l'avant"
        file: "_includes/home-section/front-section.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "activites"
        label: "Calendrier des activités"
        file: "_includes/home-section/activities.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "being"
        label: "Être"
        file: "_includes/home-section/being.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}
      - name: "contact-us"
        label: "Nous joindre"
        file: "_includes/home-section/contact-us.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Options du site"
    editor:
      preview: false
    files:
      - name: "colors"
        label: "Couleurs"
        file: "_data/colors.yml"
        fields:
          - {label: "Couleur de fond section A", name: "section-a-background", widget: "string"}
          - {label: "Couleur de fond section B", name: "section-b-background", widget: "string"}
      - name: "sitemenu"
        label: "Menu principal"
        file: "_data/sitemenu.yml"
        fields:
          - name: "pagesnav"
            label: "Pages"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Path", name: "path", widget: "string"}
          - name: "scrollnav"
            label: "Sections de la page d'accueil"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Path", name: "path", widget: "string"}


